version: '3.8'

services:
  db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=foo
      - POSTGRES_USER=VanDarkholme
      - POSTGRES_PASSWORD=300bucks

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_NAME=foo
      - POSTGRES_USER=VanDarkholme
      - POSTGRES_PASSWORD=300bucks
      - DB_HOST=db
      - DB_PORT=5432